# -*- coding: utf-8 -*-

# ==============================================================================
# AUTOGENERATED
# python.sdk.version - AUTOGENERATED
# VERSION.py - MAINTAINER's. Don't edit, if you don't know what are you doing
# ==============================================================================

VERSION = (0, 1, 0)
RELEASE_SUFFIX = '-dev.8'

VERSION_STRING = '.'.join([str(x) for x in VERSION[0:3]])
RELEASE_STRING = VERSION_STRING + RELEASE_SUFFIX

PROJECT = 'Route4Me Python SDK'
COPYRIGHT = '2016-2017 © Route4Me Python Team'
AUTHOR = 'Route4Me Python Team (SDK)'
TITLE = 'route4me-sdk'
LICENSE = 'ISC'
BUILD = None   # TRAVIS_COMMIT
COMMIT = None  # TRAVIS_BUILD_NUMBER
