# -*- coding: utf-8 -*-

# AUTOGENERATED
# ==============================================================================
VERSION = (0, 1, 0)
VERSION_SUFFIX = '-dev.4'

# TODO: gh #9 - hard-rewrite this file on Travis
BUILD = None   # TRAVIS_COMMIT
COMMIT = None  # TRAVIS_BUILD_NUMBER
# ==============================================================================

# SUFFIX
_v = [str(x) for x in VERSION[0:3]]
VERSION_STRING = '.'.join(_v) + VERSION_SUFFIX
