# -*- coding: utf-8 -*-

# AUTOGENERATED
# ==============================================================================
VERSION = (0, 1, 0)
VERSION_SUFFIX = '-dev.4'

# TODO: gh #9 - hard-rewrite this file on Travis
BUILD = None   # TRAVIS_COMMIT
COMMIT = None  # TRAVIS_BUILD_NUMBER
# ==============================================================================

VERSION_STRING = '.'.join([str(x) for x in VERSION[0:3]])
RELEASE_STRING = VERSION_STRING + VERSION_SUFFIX
